name: Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - run: node index.js
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

